name: Run Script
on: [push]
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  run-example-script:
    runs-on: ubuntu-latest
    steps:
      - name: Run Example script
        run: ./.github/scripts/my-script.sh
        shell: bash

